[package]
name = "data_structure"
version = "0.1.0"
authors = ["caoyong <caoyong@bytedance.com>"]

[[bin]]
name = "binary"
path = "src/binary.rs"

[[bin]]
name = "expr"
path = "src/expr.rs"

[workspace]
members = [
  'capacity_stack'
]

[dependencies]
elapsed = "0.1"
